### ISSUE TITLE
Error Exception bei DragnDrop-Nutzung

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/bloecks#15]
Hallo :)

schönes Add-On, absolut essentiell wie ich finde.
Allerdings endet ein DragnDrop beim Slice verschieben mit folgender Ausgabe:
```
"Error" thrown in /***/redaxo/src/addons/bloecks/plugins/dragndrop/lib/rex_api_content_move_slice_to.php on line 73
Call to protected method bloecks_abstract::package() from context 'rex_api_content_move_slice_to'

#0 /***/redaxo/src/core/lib/api_function.php(130): rex_api_content_move_slice_to->execute()
#1 /***/redaxo/src/core/backend.php(134): rex_api_function::handleCall()
#2 /***/redaxo/src/core/boot.php(105): require('***')
#3 /***/redaxo/index.php(9): require('/is/htdocs/wp11...')
#4 {main}
```

Der Fehler ist reproduzierbar. Habe auch nochmal soeben die aktuelle GitHub-Version installiert. Fehler tritt weiterhin auf. Ich benutze  ein frisch installiertes Redaxo 5.2 mit folgenden aktiven AddOns:

Adminer
blÖcks (mit den 3 Plugins)
Developer
Email Obfuscator
Focuspoint
Redactor 2
Watson
YForm
YRewrite

Kann das jemand bestätigen und besser noch beheben? Wäre grandiooos :)

**Comment by dpf-dd** [comment]
OK, Fehler kann jetzt auch bei mir nicht mehr reproduziert werden. Ich hatte die 5.2 nochmal als offizielles Release geladen und nicht aus dem github. Jedenfalls funktioniert es jetzt alles :)
